### ISSUE TITLE
Unit_01: Notebook_01 needed fixes. 

### ISSUE THREAD

**Issue by ppxasjsm** [Edinburgh-Chemistry-Teaching/Data-driven-chemistry#1]
Here is a summary of things I have noticed from the Style guide that should be fixed in Notebook 1.1. There may be more. 
- [ ] Tasks need alert success boxes. 
- [ ] TOC missing
- [ ] Maybe some additional links to more material (Jupyter documentation)
- [ ] ⚠️: I have used this symbol followed by @jasmin-guven and @hp115 to indicate you need to do something here. 
- [ ] Check heading levels and numbering.

**Comment by jasmin-guven** [comment]
> Here is a summary of things I have noticed from the Style guide that should be fixed in Notebook 1.1. There may be more.
> 
> * [ X]  Tasks need alert success boxes.
> * [X]  TOC missing
> * [X]  ⚠️: I have used this symbol followed by @jasmin-guven and @hp115 to indicate you need to do something here.
> * [ X]  Check heading levels and numbering.
> * [X ]  Maybe some additional links to more material (Jupyter documentation)


List of packages used:

- IPython.display: IFrame
- Mentimeter
