### ISSUE TITLE
Paper modifications

### ISSUE THREAD

**Issue by jcumby** [Edinburgh-Chemistry-Teaching/Data-driven-chemistry#22]
Some suggestions to the paper which should be discussed before editing:
- In the 'content' section, should references to `Unit_XX` be hyperlinked to the relevant folder, Colab notebook, or just text?
- Do we want to link to the Edinburgh DRPS entry somewhere (http://www.drps.ed.ac.uk/21-22/dpt/cxchem08031.htm)?

**Comment by ppxasjsm** [comment]
> In the 'content' section, should references to Unit_XX be hyperlinked to the relevant folder, Colab notebook, or just text?

I don't think I have a preference here. 

> Do we want to link to the Edinburgh DRPS entry somewhere (http://www.drps.ed.ac.uk/21-22/dpt/cxchem08031.htm)?

Yes I like this idea.

**Comment by ppxasjsm** [comment]
Comment on your pull request. I think we should have a better Mentimeter example figure potentially? This was meant as a placeholder.

**Comment by jcumby** [comment]
PR #24 includes a new Mentimeter figure, as requested!

**Comment by ppxasjsm** [comment]
Thank you :)
