### ISSUE TITLE
colab - cannot import a module? or files?

### ISSUE THREAD

**Issue by punkpony** [Edinburgh-Chemistry-Teaching/Data-driven-chemistry#34]
Have an issue with loading a module in Google Colab. 

It is the module moved out from Unit 08:

> Took the liberty of moving it out, and added a little text with extra explanation. Personally I find it clearer.
_Originally posted by @degiacom in https://github.com/Edinburgh-Chemistry-Teaching/Data-driven-chemistry/issues/4#issuecomment-1369645281_
      
It works fine in Jupiter Notebooks, Binder is also fine.

Error I am getting in Google Colab is:
```
import molecule_getter as mg
m, w = mg.get_molecule()
```

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-7e70cc318175>](https://godmawlgd9t-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230109-060104-RC00_500662758#) in <module>
----> 1 import molecule_getter as mg
      2 m, w = mg.get_molecule()

ModuleNotFoundError: No module named 'molecule_getter'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

Unsure if this is a particular issue with this module/Unit, or a more general one - hence new issue, so we can double check:)

**Comment by punkpony** [comment]
**UPDATE:**
There seem to be an issue with reading in files into colab, i.e. also cannot import a structure file.
We basically need to _clone the git into colab_ or _load the files we need_ into colab. 

> **Load individual files directly from GitHub**
> In case you just have to work with a few files rather than the entire repository, you can load them directly from GitHub without needing to clone the repository to Colab.
> 
> To do this:
> - click on the file in the repository, 
> - click on 'View Raw',
> - copy the URL of the raw file, 
> - use this URL as the location of your file. 
from: https://neptune.ai/blog/google-colab-dealing-with-files 

Not sure what is the best solution to make colab work

**Comment by ppxasjsm** [comment]
I think we decided to move away from Colab and just focus on getting binder to work. But these are all really useful bonuses but not essential.

**Comment by ppxasjsm** [comment]
And yes binder loading takes FOREVER

**Comment by punkpony** [comment]
does this help?
https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956/2 

I like binder, but the pain of building is ... a pain.

I guess we have quite a heavy bit of code there, so it will never be fast

**Comment by ppxasjsm** [comment]
Thanks! Yes this may help.

**Comment by ppxasjsm** [comment]
Colab now works fine. Closing this issue
