### ISSUE TITLE
Error launching binder

### ISSUE THREAD

**Issue by lucydot** [Edinburgh-Chemistry-Teaching/Data-driven-chemistry#39]
Hello,

Another one whilst working through the JOSE review (https://github.com/openjournals/jose-reviews/issues/192).

I'm unable to launch binder via the link given on the README (only tested for parts 1 and 2). The error is [here](https://gist.github.com/lucydot/e3b996b56bd8509a296979375f0fde8a).

**Comment by ppxasjsm** [comment]
Ah yes, I may have broken this trying to fix NGLview, still trying to get this to work..fixing this is definitely on the to do list.

**Comment by ppxasjsm** [comment]
I couldn't get Binder to work in a fast way (I saw you can do prebuilds of docker containers with github actions, but it seemed like faff to figure out how to do that). Also NglView was a pain, so I migrated to Colab. This should be all up and running now.

**Comment by lucydot** [comment]
Fab! I've just opened in my browser and ran through the first few tutorials - they are working well.
