### ISSUE TITLE
Unit_05_II_plotting Task 1.1: plt.savefig does not work on Colab 

### ISSUE THREAD

**Issue by jasmin-guven** [Edinburgh-Chemistry-Teaching/Data-driven-chemistry#41]
Trying to save the plotted figure to `images/myfigure.png` results in an error. 

My guess is that we need to copy the `images` directory as is done with `data` at the start?

```
try:
    import google.colab
    IN_COLAB = True
except:
    IN_COLAB = False
if IN_COLAB:
    # copy over data repository
    !git clone https://github.com/Edinburgh-Chemistry-Teaching/Data-driven-chemistry
    !cp -r Data-driven-chemistry/Unit_05/data .
```

![Screenshot 2023-03-01 at 11 18 50](https://user-images.githubusercontent.com/57833295/222124833-18b729c6-30ff-4008-a594-ea78ec9884dd.png)

**Comment by ppxasjsm** [comment]
I can fix this!

**Comment by ppxasjsm** [comment]
2201faa fixes this.
