### ISSUE TITLE
proofs edits

### ISSUE THREAD

**Issue by clhobday** [Edinburgh-Chemistry-Teaching/Data-driven-chemistry#51]
I only have two small grammatical changes. 

page 2:
During the first lecture, the 2022/23 cohort was asked the question: “Do you know how to code?” Overwhelmingly (62%), students replied with “I have no prior coding experience,” while an additional 30% replied - “I only have some basic Python or coding experience.” Only one respondent answered that they were confident in the use of Python.

should read:
During the first lecture, the 2022/23 cohort was asked the question: “Do you know how to code?”. Overwhelmingly (62%), students replied with “I have no prior coding experience,” while an additional 30% replied - “I only have some basic Python or coding experience”. Only one respondent answered that they were confident in the use of Python.

page 3 NBGrader should read nbgrader

**Comment by ppxasjsm** [comment]
Fixed in 8dae537 with some additional minor changes
